In [19]:
import pandas as pd
import numpy as np
from pandas import Series, DataFrame
from pandas import read_html


In [20]:
#open with html

url = 'https://www.fdic.gov/resources/resolutions/bank-failures/failed-bank-list/banklist.html'

In [21]:
df= pd.io.html.read_html(url)

In [22]:
df[0]

Bank Name           City  ST   CERT  \
0                 The First State Bank  Barboursville  WV  14361   
1                   Ericson State Bank        Ericson  NE  18265   
2     City National Bank of New Jersey         Newark  NJ  21111   
3                        Resolute Bank         Maumee  OH  58317   
4                Louisa Community Bank         Louisa  KY  58112   
..                                 ...            ...  ..    ...   
556                 Superior Bank, FSB       Hinsdale  IL  32646   
557                Malta National Bank          Malta  OH   6629   
558    First Alliance Bank & Trust Co.     Manchester  NH  34264   
559  National State Bank of Metropolis     Metropolis  IL   3815   
560                   Bank of Honolulu       Honolulu  HI  21029   

                   Acquiring Institution       Closing Date  
0                         MVB Bank, Inc.      April 3, 2020  
1             Farmers and Merchants Bank  February 14, 2020  
2                        Industrial Bank   November 1, 2019  
3                     Buckeye State Bank   October 25, 2019  
4      Kentucky Farmers Bank Corporation   October 25, 2019  
..                                   ...                ...  
556                Superior Federal, FSB      July 27, 2001  
557                    North Valley Bank        May 3, 2001  
558  Southern New Hampshire Bank & Trust   February 2, 2001  
559              Banterra Bank of Marion  December 14, 2000  
560                   Bank of the Orient   October 13, 2000  

[561 rows x 6 columns]

In [23]:
#open with excel file 

xlsfile = pd.ExcelFile('C://Users//user//Desktop//adult.xlsx')
xlsfile.parse('Sheet1')

Unnamed: 0   0                  1       2            3   4  \
0               0  39          State-gov   77516    Bachelors  13   
1               1  50   Self-emp-not-inc   83311    Bachelors  13   
2               2  38            Private  215646      HS-grad   9   
3               3  53            Private  234721         11th   7   
4               4  28            Private  338409    Bachelors  13   
...           ...  ..                ...     ...          ...  ..   
32556       32556  27            Private  257302   Assoc-acdm  12   
32557       32557  40            Private  154374      HS-grad   9   
32558       32558  58            Private  151910      HS-grad   9   
32559       32559  22            Private  201490      HS-grad   9   
32560       32560  52       Self-emp-inc  287927      HS-grad   9   

                         5                   6               7       8  \
0            Never-married        Adm-clerical   Not-in-family   White   
1       Married-civ-spouse     Exec-managerial         Husband   White   
2                 Divorced   Handlers-cleaners   Not-in-family   White   
3       Married-civ-spouse   Handlers-cleaners         Husband   Black   
4       Married-civ-spouse      Prof-specialty            Wife   Black   
...                    ...                 ...             ...     ...   
32556   Married-civ-spouse        Tech-support            Wife   White   
32557   Married-civ-spouse   Machine-op-inspct         Husband   White   
32558              Widowed        Adm-clerical       Unmarried   White   
32559        Never-married        Adm-clerical       Own-child   White   
32560   Married-civ-spouse     Exec-managerial            Wife   White   

             9     10  11  12              13      14  
0         Male   2174   0  40   United-States   <=50K  
1         Male      0   0  13   United-States   <=50K  
2         Male      0   0  40   United-States   <=50K  
3         Male      0   0  40   United-States   <=50K  
4       Female      0   0  40            Cuba   <=50K  
...        ...    ...  ..  ..             ...     ...  
32556   Female      0   0  38   United-States   <=50K  
32557     Male      0   0  40   United-States    >50K  
32558   Female      0   0  40   United-States   <=50K  
32559     Male      0   0  20   United-States   <=50K  
32560   Female  15024   0  40   United-States    >50K  

[32561 rows x 16 columns]

In [33]:
#merge 

df1 = DataFrame({'key':['x','x','y','y','z','y'],'data':np.arange(6)})
df1

key  data
0   x     0
1   x     1
2   y     2
3   y     3
4   z     4
5   y     5

In [34]:
df2 = DataFrame({'key':['w','z','y'],'data':[1,2,3]})
df2

key  data
0   w     1
1   z     2
2   y     3

In [31]:
pd.merge(df1,df2)


key  data
0   y     3

In [32]:
pd.merge(df1,df2,on='key')

key  data_x  data_y
0   y       2       3
1   y       3       3
2   y       5       3
3   z       4       2

In [36]:
pd.merge(df1,df2,on='key',how='left') #pass them using the left data

key  data_x  data_y
0   x       0     NaN
1   x       1     NaN
2   y       2     3.0
3   y       3     3.0
4   z       4     2.0
5   y       5     3.0

In [37]:
pd.merge(df1,df2,on='key',how='right')

key  data_x  data_y
0   y     2.0       3
1   y     3.0       3
2   y     5.0       3
3   z     4.0       2
4   w     NaN       1

In [80]:
df_left = DataFrame({'key1':['NYC','BS','LA'],
                    'key2':['one','two','three'],
                    'left_data':[10,20,30]})

df_right = DataFrame({'key1':['NYC','BS','LA','LA'],
                    'key2':['one','two','three','two'],
                    'left_data':[30,50,60,70]})

In [81]:
df_left

key1   key2  left_data
0  NYC    one         10
1   BS    two         20
2   LA  three         30

In [82]:
df_right

key1   key2  left_data
0  NYC    one         30
1   BS    two         50
2   LA  three         60
3   LA    two         70

In [84]:
pd.merge(df_left,df_right,on=['key1','key2'],how='outer')

key1   key2  left_data_x  left_data_y
0  NYC    one         10.0           30
1   BS    two         20.0           50
2   LA  three         30.0           60
3   LA    two          NaN           70

In [85]:
pd.merge(df_left,df_right,on=['key1'])

key1 key2_x  left_data_x key2_y  left_data_y
0  NYC    one           10    one           30
1   BS    two           20    two           50
2   LA  three           30  three           60
3   LA  three           30    two           70

In [86]:
pd.merge(df_left,df_right,on=['key1'],suffixes=('_lefty','_righty'))

key1 key2_lefty  left_data_lefty key2_righty  left_data_righty
0  NYC        one               10         one                30
1   BS        two               20         two                50
2   LA      three               30       three                60
3   LA      three               30         two                70

In [87]:
#merge on index 

df_a = DataFrame({'key':['A','B','A','C','D'],'data':range(5)})
df_b = DataFrame({'group_data':[10,20]},index=['A','B'])
pd.merge(df_a,df_b,left_on='key',right_index=True)

key  data  group_data
0   A     0          10
2   A     2          10
1   B     1          20

In [88]:
df_left_hr = DataFrame({'key1':['NYC','BS','LA','LA','NYC'],
                    'key2':[10,20,30,20,30],
                    'data_set':np.arange(5)})
df_left_hr

key1  key2  data_set
0  NYC    10         0
1   BS    20         1
2   LA    30         2
3   LA    20         3
4  NYC    30         4

In [89]:
df_right_hr = DataFrame(np.arange(10).reshape(5,2),index=[['LA','LA','SF','SF','SF'],[10,20,30,20,10]],columns=['col1','col2'])

df_right_hr

col1  col2
LA 10     0     1
   20     2     3
SF 30     4     5
   20     6     7
   10     8     9

In [90]:
pd.merge(df_left_hr,df_right_hr,left_on=['key1','key2'],right_index=True)

key1  key2  data_set  col1  col2
3   LA    20         3     2     3

In [91]:
#concatenate :noi 

arr1 =np.arange(9).reshape(3,3)
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [93]:
np.concatenate([arr1,arr1],axis=0) #theo cot

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [94]:
np.concatenate([arr1,arr1],axis=1) #theo dong

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [98]:
ser1 = Series([0,1,2], index=['a','b','c'])
ser2= Series([4,6], index=['e','f'])

pd.concat([ser1,ser2],axis=1)

0    1
a  0.0  NaN
b  1.0  NaN
c  2.0  NaN
e  NaN  4.0
f  NaN  6.0

In [99]:
pd.concat([ser1,ser2],keys=['cat1','cat2'])

cat1  a    0
      b    1
      c    2
cat2  e    4
      f    6
dtype: int64

In [103]:
df1 = DataFrame(np.random.randn(4,3),columns=['cot1','cot2','cot3'])
dr2= DataFrame(np.random.randn(3,5),columns=['cot1','cot2','c3','c4','c5'])
pd.concat([df1,df2])

cot1      cot2      cot3  key  data
0  1.159282  0.109958 -0.372127  NaN   NaN
1  0.017030 -1.159342 -1.615605  NaN   NaN
2 -1.423958 -0.991634  0.251056  NaN   NaN
3 -0.064131  0.047977  0.049814  NaN   NaN
0       NaN       NaN       NaN    w   1.0
1       NaN       NaN       NaN    z   2.0
2       NaN       NaN       NaN    y   3.0

In [104]:
pd.concat([df1,df2],ignore_index=True)

cot1      cot2      cot3  key  data
0  1.159282  0.109958 -0.372127  NaN   NaN
1  0.017030 -1.159342 -1.615605  NaN   NaN
2 -1.423958 -0.991634  0.251056  NaN   NaN
3 -0.064131  0.047977  0.049814  NaN   NaN
4       NaN       NaN       NaN    w   1.0
5       NaN       NaN       NaN    z   2.0
6       NaN       NaN       NaN    y   3.0

In [108]:
# combine dataframe

ser1 = Series([2,np.nan,4,np.nan,6,np.nan],index=['A','B','C','D','E','F'])
ser1



A    2.0
B    NaN
C    4.0
D    NaN
E    6.0
F    NaN
dtype: float64

In [110]:
ser2 = Series(np.arange(len(ser1)),dtype=np.float64,index=['A','B','C','D','E','F'])
ser2

A    0.0
B    1.0
C    2.0
D    3.0
E    4.0
F    5.0
dtype: float64

In [111]:
Series(np.where(pd.isnull(ser1),ser2,ser1),index=ser1.index)

A    2.0
B    1.0
C    4.0
D    3.0
E    6.0
F    5.0
dtype: float64

In [112]:
ser1.combine_first(ser2)

A    2.0
B    1.0
C    4.0
D    3.0
E    6.0
F    5.0
dtype: float64

In [114]:
nan = np.nan

dframe1 = DataFrame({'x':[1,nan,3,nan],
                    'y':[2,nan,nan,8],
                    'z':[nan,2,4,5]})
dframe2 = DataFrame({'x':[1,2,nan,2],
                    'y':[4,3,4,8]
                      })

dframe1.combine_first(dframe2)

x    y    z
0  1.0  2.0  NaN
1  2.0  3.0  2.0
2  3.0  4.0  4.0
3  2.0  8.0  5.0

In [115]:
#reshape

df1 = DataFrame(np.arange(8).reshape(2,4),
               index=pd.Index(['LA','SF'],name='city'),
               columns = pd.Index(['a','b','c','d'], name='letter'))
df1

letter  a  b  c  d
city              
LA      0  1  2  3
SF      4  5  6  7

In [118]:
df_St = df1.stack()  #stack or unstack
df_St

city  letter
LA    a         0
      b         1
      c         2
      d         3
SF    a         4
      b         5
      c         6
      d         7
dtype: int32

In [119]:
df_St.unstack('city')

city    LA  SF
letter        
a        0   4
b        1   5
c        2   6
d        3   7

In [ ]:
#pivot table

#df_pivot = df.pivot('ten cot1','ten cot 2')

In [132]:
#duplicates in dataframes

df_x = DataFrame({'key1':['a','a','b','b','b'], 'key2': [2,2,3,3,2]})
df_x
                            

key1  key2
0    a     2
1    a     2
2    b     3
3    b     3
4    b     2

In [133]:
df_x.duplicated()  

0    False
1     True
2    False
3     True
4    False
dtype: bool

In [131]:
df_x.drop_duplicates()

key1  key2
0    a     2
2    b     3
4    b     2

In [136]:
df_x.drop_duplicates('key1')

key1  key2
0    a     2
2    b     3

In [139]:
#maping 

df = DataFrame({'city': ['NewYork','Boston','Cali'],
               'altitude': [3134,5255,5463]})

df


city  altitude
0  NewYork      3134
1   Boston      5255
2     Cali      5463

In [141]:
state_map = {'NewYork':'Colorano','Boston':'Uhat','Cali':'ohoh'}

df['state'] = df['city'].map(state_map)
df

city  altitude     state
0  NewYork      3134  Colorano
1   Boston      5255      Uhat
2     Cali      5463      ohoh

In [145]:
#replace

ser = Series([1,2,3,4,1,2,3,4])

ser.replace(1,np.nan) #

0    NaN
1    2.0
2    3.0
3    4.0
4    NaN
5    2.0
6    3.0
7    4.0
dtype: float64

In [146]:
ser.replace([1,4],[100,400])

0    100
1      2
2      3
3    400
4    100
5      2
6      3
7    400
dtype: int64

In [154]:
#rename index

df1 = DataFrame(np.arange(12).reshape(3,4),index=['A','B','C'],columns=['Cot1','cot2','cot3','COT4'])
df1

Cot1  cot2  cot3  COT4
A     0     1     2     3
B     4     5     6     7
C     8     9    10    11

In [160]:
df1.index.map(str.lower)
df1.index = df.index.map(str.lower)

In [163]:
df1

Cot1  cot2  cot3  COT4
a     0     1     2     3
b     4     5     6     7
c     8     9    10    11

In [164]:
df1.rename(index=str.title, columns=str.lower)

cot1  cot2  cot3  cot4
A     0     1     2     3
B     4     5     6     7
C     8     9    10    11

In [168]:
df1.rename(index={'a':'California'}, columns={'Cot1':'column1'})

column1  cot2  cot3  COT4
California        0     1     2     3
b                 4     5     6     7
c                 8     9    10    11

In [170]:
#Binning

years = [1990,1992,1888,1224,1878,1956,1976]
decade_bins =[1970,1980,1990,2000,2010,2020]

In [172]:
decade_cat =pd.cut(years,decade_bins)
decade_cat

[(1980.0, 1990.0], (1990.0, 2000.0], NaN, NaN, NaN, NaN, (1970.0, 1980.0]]
Categories (5, interval[int64]): [(1970, 1980] < (1980, 1990] < (1990, 2000] < (2000, 2010] < (2010, 2020]]

In [173]:
decade_cat.categories

IntervalIndex([(1970, 1980], (1980, 1990], (1990, 2000], (2000, 2010], (2010, 2020]],
              closed='right',
              dtype='interval[int64]')

In [176]:
pd.value_counts(decade_cat)

(1990, 2000]    1
(1980, 1990]    1
(1970, 1980]    1
(2010, 2020]    0
(2000, 2010]    0
dtype: int64

In [177]:
pd.cut(years,2,precision=1) # 2 is a how many bins you wanna cut i into

[(1608.0, 1992.0], (1608.0, 1992.0], (1608.0, 1992.0], (1223.2, 1608.0], (1608.0, 1992.0], (1608.0, 1992.0], (1608.0, 1992.0]]
Categories (2, interval[float64]): [(1223.2, 1608.0] < (1608.0, 1992.0]]

In [178]:
#outliers

np.random.seed(12345)
df = DataFrame(np.random.randn(1000,4))
df.head()

0         1         2         3
0 -0.204708  0.478943 -0.519439 -0.555730
1  1.965781  1.393406  0.092908  0.281746
2  0.769023  1.246435  1.007189 -1.296221
3  0.274992  0.228913  1.352917  0.886429
4 -2.001637 -0.371843  1.669025 -0.438570

In [179]:
col =df[0]
col.head()

0   -0.204708
1    1.965781
2    0.769023
3    0.274992
4   -2.001637
Name: 0, dtype: float64

In [180]:
col[np.abs(col)>3]

#row number 523 and 900 had absolute ( gia tri tuyet doi )greater than 3

523   -3.428254
900    3.366626
Name: 0, dtype: float64

In [181]:
df[(np.abs(df)>3).any(1)]

#return every row where column has absolute greater than 3

0         1         2         3
5   -0.539741  0.476985  3.248944 -1.021228
97  -0.774363  0.552936  0.106061  3.927528
102 -0.655054 -0.565230  3.176873  0.959533
305 -2.315555  0.457246 -0.025907 -3.399312
324  0.050188  1.951312  3.260383  0.963301
400  0.146326  0.508391 -0.196713 -3.745356
499 -0.293333 -0.242459 -3.056990  1.918403
523 -3.428254 -0.296336 -0.439938 -0.867165
586  0.275144  1.179227 -3.184377  1.369891
808 -0.362528 -3.548824  1.553205 -2.186301
900  3.366626 -2.372214  0.851010  1.332846

In [182]:
df[np.abs(df)>3] = np.sign(df)*3

In [184]:
df.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.067623     0.068473     0.025153    -0.002081
std       0.995485     0.990253     1.003977     0.989736
min      -3.000000    -3.000000    -3.000000    -3.000000
25%      -0.774890    -0.591841    -0.641675    -0.644144
50%      -0.116401     0.101143     0.002073    -0.013611
75%       0.616366     0.780282     0.680391     0.654328
max       3.000000     2.653656     3.000000     3.000000

In [185]:
#permutation : hoan vi

df = DataFrame(np.arange(16).reshape(4,4))
blender = np.random.permutation(4)
blender

array([1, 3, 2, 0])

In [186]:
df

0   1   2   3
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15

In [187]:
df.take(blender)

0   1   2   3
1   4   5   6   7
3  12  13  14  15
2   8   9  10  11
0   0   1   2   3